export const PERMISSIONS_MAP = {
  // 相机
  'android.permission.CAMERA': { desc: '拍照和录像', level: 'danger' },

  // 联系人
  'android.permission.READ_CONTACTS': { desc: '读取联系人', level: 'danger' },
  'android.permission.WRITE_CONTACTS': { desc: '修改联系人', level: 'danger' },
  'android.permission.GET_ACCOUNTS': { desc: '访问账户列表', level: 'warning' },
  'android.permission.MANAGE_ACCOUNTS': { desc: '管理账户', level: 'danger' },
  'android.permission.ADD_VOICEMAIL': { desc: '添加语音邮件', level: 'danger' },

  // 电话
  'android.permission.CALL_PHONE': { desc: '直接拨打电话', level: 'danger' },
  'android.permission.READ_PHONE_STATE': { desc: '读取电话状态', level: 'danger' },
  'android.permission.READ_CALL_LOG': { desc: '读取通话记录', level: 'danger' },
  'android.permission.WRITE_CALL_LOG': { desc: '修改通话记录', level: 'danger' },
  'android.permission.PROCESS_OUTGOING_CALLS': { desc: '监听外拨电话', level: 'danger' },
  'android.permission.ANSWER_PHONE_CALLS': { desc: '接听电话', level: 'danger' },
  'android.permission.READ_PHONE_NUMBERS': { desc: '读取手机号码', level: 'danger' },
  'android.permission.CALL_PRIVILEGED': { desc: '拨打特权号码', level: 'danger' },
  'android.permission.READ_VOICEMAIL': { desc: '读取语音邮件', level: 'danger' },
  'android.permission.WRITE_VOICEMAIL': { desc: '修改语音邮件', level: 'danger' },
  'android.permission.BIND_INCALL_SERVICE': { desc: '通话界面服务', level: 'danger' },
  'android.permission.BIND_TELECOM_CONNECTION_SERVICE': { desc: '电话连接服务', level: 'warning' },

  // 短信
  'android.permission.SEND_SMS': { desc: '发送短信', level: 'danger' },
  'android.permission.RECEIVE_SMS': { desc: '接收短信', level: 'danger' },
  'android.permission.READ_SMS': { desc: '读取短信', level: 'danger' },
  'android.permission.WRITE_SMS': { desc: '编辑短信', level: 'danger' },
  'android.permission.RECEIVE_MMS': { desc: '接收彩信', level: 'danger' },
  'android.permission.RECEIVE_WAP_PUSH': { desc: '接收 WAP 推送', level: 'danger' },
  'android.permission.READ_CELL_BROADCASTS': { desc: '读取小区广播', level: 'warning' },
  'android.permission.SEND_RESPOND_VIA_MESSAGE': { desc: '短信拒接来电', level: 'danger' },

  // 位置
  'android.permission.ACCESS_FINE_LOCATION': { desc: '精确位置 (GPS)', level: 'danger' },
  'android.permission.ACCESS_COARSE_LOCATION': { desc: '粗略位置 (网络)', level: 'warning' },
  'android.permission.ACCESS_BACKGROUND_LOCATION': { desc: '后台获取位置', level: 'danger' },
  'android.permission.ACCESS_LOCATION_EXTRA_COMMANDS': { desc: '额外位置信息', level: 'normal' },
  'android.permission.INSTALL_LOCATION_PROVIDER': { desc: '安装位置服务', level: 'danger' },

  // 存储
  'android.permission.READ_EXTERNAL_STORAGE': { desc: '读取存储空间', level: 'warning' },
  'android.permission.WRITE_EXTERNAL_STORAGE': { desc: '修改存储空间', level: 'warning' },
  'android.permission.MANAGE_EXTERNAL_STORAGE': { desc: '管理所有文件', level: 'danger' },
  'android.permission.READ_MEDIA_IMAGES': { desc: '读取图片', level: 'warning' },
  'android.permission.READ_MEDIA_VIDEO': { desc: '读取视频', level: 'warning' },
  'android.permission.READ_MEDIA_AUDIO': { desc: '读取音频', level: 'warning' },
  'android.permission.READ_MEDIA_VISUAL_USER_SELECTED': { desc: '读取部分媒体', level: 'warning' },
  'android.permission.WRITE_MEDIA_STORAGE': { desc: '写入媒体存储', level: 'warning' },

  // 网络
  'android.permission.INTERNET': { desc: '网络访问', level: 'normal' },
  'android.permission.ACCESS_NETWORK_STATE': { desc: '查看网络状态', level: 'normal' },
  'android.permission.ACCESS_WIFI_STATE': { desc: '查看 Wi-Fi 状态', level: 'normal' },
  'android.permission.CHANGE_WIFI_STATE': { desc: '修改 Wi-Fi 状态', level: 'warning' },
  'android.permission.CHANGE_NETWORK_STATE': { desc: '修改网络状态', level: 'warning' },
  'android.permission.BLUETOOTH': { desc: '蓝牙连接', level: 'warning' },
  'android.permission.BLUETOOTH_ADMIN': { desc: '蓝牙管理', level: 'warning' },
  'android.permission.BLUETOOTH_CONNECT': { desc: '蓝牙连接设备', level: 'warning' },
  'android.permission.BLUETOOTH_SCAN': { desc: '扫描蓝牙设备', level: 'warning' },
  'android.permission.BLUETOOTH_ADVERTISE': { desc: '蓝牙广播', level: 'warning' },
  'android.permission.NFC': { desc: 'NFC 近场通信', level: 'warning' },
  'android.permission.NFC_PREFERRED_PAYMENT_INFO': { desc: 'NFC 支付信息', level: 'warning' },
  'android.permission.ACCESS_WIMAX_STATE': { desc: '查看 WiMAX 状态', level: 'normal' },
  'android.permission.CHANGE_WIMAX_STATE': { desc: '修改 WiMAX 状态', level: 'warning' },
  'android.permission.LOADER_USAGE_STATS': { desc: '加载器使用统计', level: 'warning' },

  // 传感器
  'android.permission.BODY_SENSORS': { desc: '身体传感器', level: 'danger' },
  'android.permission.BODY_SENSORS_BACKGROUND': { desc: '后台身体传感器', level: 'danger' },
  'android.permission.ACTIVITY_RECOGNITION': { desc: '活动识别', level: 'warning' },
  'android.permission.HIGH_SAMPLING_RATE_SENSORS': { desc: '高频传感器数据', level: 'warning' },

  // 录音
  'android.permission.RECORD_AUDIO': { desc: '录音', level: 'danger' },

  // 日历
  'android.permission.READ_CALENDAR': { desc: '读取日历', level: 'danger' },
  'android.permission.WRITE_CALENDAR': { desc: '修改日历', level: 'danger' },

  // 系统
  'android.permission.VIBRATE': { desc: '振动', level: 'normal' },
  'android.permission.WAKE_LOCK': { desc: '防止休眠', level: 'normal' },
  'android.permission.RECEIVE_BOOT_COMPLETED': { desc: '开机自启动', level: 'warning' },
  'android.permission.SYSTEM_ALERT_WINDOW': { desc: '悬浮窗', level: 'warning' },
  'android.permission.REQUEST_INSTALL_PACKAGES': { desc: '安装应用', level: 'danger' },
  'android.permission.FOREGROUND_SERVICE': { desc: '前台服务', level: 'normal' },
  'android.permission.FOREGROUND_SERVICE_SPECIAL_USE': { desc: '特殊前台服务', level: 'warning' },
  'android.permission.FOREGROUND_SERVICE_CAMERA': { desc: '相机前台服务', level: 'warning' },
  'android.permission.FOREGROUND_SERVICE_MICROPHONE': { desc: '麦克风前台服务', level: 'warning' },
  'android.permission.FOREGROUND_SERVICE_LOCATION': { desc: '位置前台服务', level: 'warning' },
  'android.permission.FOREGROUND_SERVICE_DATA_SYNC': { desc: '数据同步前台服务', level: 'normal' },
  'android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK': { desc: '媒体播放前台服务', level: 'normal' },
  'android.permission.POST_NOTIFICATIONS': { desc: '发送通知', level: 'normal' },
  'android.permission.SET_ALARM': { desc: '设置闹钟', level: 'normal' },
  'android.permission.INSTALL_SHORTCUT': { desc: '创建快捷方式', level: 'normal' },
  'android.permission.UNINSTALL_SHORTCUT': { desc: '删除快捷方式', level: 'normal' },
  'android.permission.EXPAND_STATUS_BAR': { desc: '展开状态栏', level: 'normal' },
  'android.permission.DISABLE_KEYGUARD': { desc: '禁用锁屏', level: 'warning' },
  'android.permission.USE_EXACT_ALARM': { desc: '精确闹钟', level: 'warning' },
  'android.permission.SCHEDULE_EXACT_ALARM': { desc: '调度精确闹钟', level: 'warning' },
  'android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS': { desc: '忽略电池优化', level: 'warning' },
  'android.permission.CHANGE_WIFI_MULTICAST_STATE': { desc: 'Wi-Fi 组播', level: 'warning' },
  'android.permission.NEARBY_WIFI_DEVICES': { desc: '附近 Wi-Fi 设备', level: 'warning' },
  'android.permission.ACCESS_NOTIFICATION_POLICY': { desc: '勿扰模式', level: 'warning' },
  'android.permission.TRANSMIT_IR': { desc: '红外发射', level: 'normal' },
  'android.permission.USE_SIP': { desc: 'SIP 视频通话', level: 'warning' },
  'android.permission.READ_EXTERNAL_MEDIA': { desc: '读取外部媒体', level: 'warning' },
  'android.permission.PERSISTENT_ACTIVITY': { desc: '持久化活动', level: 'warning' },
  'android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS': { desc: '关闭系统对话框', level: 'warning' },

  // 账号
  'android.permission.AUTHENTICATE_ACCOUNTS': { desc: '管理账户', level: 'warning' },
  'android.permission.USE_CREDENTIALS': { desc: '使用账户凭证', level: 'danger' },

  // 硬件
  'android.permission.FLASHLIGHT': { desc: '使用闪光灯', level: 'normal' },
  'android.permission.USE_FINGERPRINT': { desc: '指纹识别', level: 'warning' },
  'android.permission.USE_BIOMETRIC': { desc: '生物识别', level: 'warning' },
  'android.permission.CONTROL_VPN': { desc: '控制 VPN', level: 'warning' },
  'android.permission.MANAGE_USB': { desc: '管理 USB', level: 'warning' },
  'android.permission.ACCESS_MOCK_LOCATION': { desc: '模拟位置', level: 'warning' },

  // 开发/调试
  'android.permission.READ_LOGS': { desc: '读取日志', level: 'danger' },
  'android.permission.WRITE_SETTINGS': { desc: '修改系统设置', level: 'warning' },
  'android.permission.WRITE_SECURE_SETTINGS': { desc: '修改安全设置', level: 'danger' },
  'android.permission.DUMP': { desc: '转储系统信息', level: 'danger' },
  'android.permission.DEVICE_POWER': { desc: '电源控制', level: 'danger' },

  // 其他
  'android.permission.QUERY_ALL_PACKAGES': { desc: '查询已安装应用', level: 'warning' },
  'android.permission.REQUEST_DELETE_PACKAGES': { desc: '请求卸载应用', level: 'warning' },
  'android.permission.BIND_ACCESSIBILITY_SERVICE': { desc: '无障碍服务', level: 'warning' },
  'android.permission.PACKAGE_USAGE_STATS': { desc: '使用统计', level: 'danger' },
  'android.permission.READ_SYNC_SETTINGS': { desc: '读取同步设置', level: 'normal' },
  'android.permission.WRITE_SYNC_SETTINGS': { desc: '修改同步设置', level: 'normal' },
  'android.permission.BROADCAST_STICKY': { desc: '发送粘性广播', level: 'normal' },
  'android.permission.KILL_BACKGROUND_PROCESSES': { desc: '关闭后台进程', level: 'warning' },
  'android.permission.REORDER_TASKS': { desc: '调整任务顺序', level: 'normal' },
  'android.permission.READ_PROFILE': { desc: '读取个人资料', level: 'danger' },
  'android.permission.WRITE_PROFILE': { desc: '修改个人资料', level: 'danger' },
  'android.permission.SOCIAL_STREAM': { desc: '社交信息流', level: 'danger' },
  'android.permission.READ_SOCIAL_STREAM': { desc: '读取社交信息', level: 'danger' },
  'android.permission.WRITE_SOCIAL_STREAM': { desc: '修改社交信息', level: 'danger' },
  'android.permission.READ_HISTORY_BOOKMARKS': { desc: '读取书签历史', level: 'warning' },
  'android.permission.WRITE_HISTORY_BOOKMARKS': { desc: '修改书签历史', level: 'warning' },
  'android.permission.CLEAR_APP_CACHE': { desc: '清除应用缓存', level: 'warning' },
  'android.permission.GET_TASKS': { desc: '获取运行任务', level: 'warning' },
  'android.permission.RESTART_PACKAGES': { desc: '重启应用包', level: 'warning' },
  'android.permission.SET_WALLPAPER': { desc: '设置壁纸', level: 'normal' },
  'android.permission.SET_WALLPAPER_HINTS': { desc: '设置壁纸提示', level: 'normal' },
  'android.permission.BATTERY_STATS': { desc: '电池统计', level: 'normal' },
  'android.permission.MASTER_CLEAR': { desc: '恢复出厂设置', level: 'danger' },
  'android.permission.MODIFY_AUDIO_SETTINGS': { desc: '修改音频设置', level: 'warning' },
  'android.permission.MODIFY_PHONE_STATE': { desc: '修改电话状态', level: 'danger' },
  'android.permission.MOUNT_UNMOUNT_FILESYSTEMS': { desc: '挂载文件系统', level: 'warning' },
  'android.permission.READ_FRAME_BUFFER': { desc: '读取帧缓冲', level: 'danger' },
  'android.permission.STATUS_BAR': { desc: '状态栏', level: 'warning' },
  'android.permission.ACCESS_SURFACE_FLINGER': { desc: '访问 SurfaceFlinger', level: 'danger' },
  'android.permission.INJECT_EVENTS': { desc: '注入事件', level: 'danger' },
  'android.permission.FORCE_STOP_PACKAGES': { desc: '强制停止应用', level: 'warning' },
  'android.permission.RETRIEVE_WINDOW_CONTENT': { desc: '获取窗口内容', level: 'danger' },
  'android.permission.WRITE_APN_SETTINGS': { desc: '修改 APN 设置', level: 'danger' },
  'android.permission.SUBSCRIBED_FEEDS_READ': { desc: '读取订阅源', level: 'normal' },
  'android.permission.SUBSCRIBED_FEEDS_WRITE': { desc: '修改订阅源', level: 'warning' },
  'android.permission.READ_INSTALL_SESSIONS': { desc: '读取安装会话', level: 'normal' },
  'android.permission.DELETE_PACKAGES': { desc: '删除应用包', level: 'danger' },
  'android.permission.CHANGE_COMPONENT_ENABLED_STATE': { desc: '修改组件启用状态', level: 'danger' },
  'android.permission.ACCESS_DOWNLOAD_MANAGER': { desc: '访问下载管理器', level: 'warning' },
  'android.permission.DOWNLOAD_WITHOUT_NOTIFICATION': { desc: '静默下载', level: 'warning' },
  'android.permission.ACCESS_ALL_DOWNLOADS': { desc: '访问所有下载', level: 'warning' },
  'android.permission.ACCESS_CACHE_FILESYSTEM': { desc: '访问缓存文件系统', level: 'danger' },
  'android.permission.READ_INPUT_STATE': { desc: '读取输入状态', level: 'danger' },
  'android.permission.BIND_INPUT_METHOD': { desc: '绑定输入法', level: 'warning' },
  'android.permission.BIND_WALLPAPER': { desc: '绑定壁纸', level: 'warning' },
  'android.permission.BIND_DEVICE_ADMIN': { desc: '绑定设备管理', level: 'danger' },
  'android.permission.BIND_NOTIFICATION_LISTENER_SERVICE': { desc: '通知监听服务', level: 'danger' },
  'android.permission.BIND_JOB_SERVICE': { desc: '绑定任务服务', level: 'normal' },
  'android.permission.INTERACT_ACROSS_USERS_FULL': { desc: '跨用户交互', level: 'danger' },
  'android.permission.GET_INTENT_SENDER_INTENT': { desc: '获取意图发送者', level: 'warning' },
  'android.permission.READ_CONTACTS_PROVIDER_ALLOW_NON_SYNC': { desc: '非同步读取联系人', level: 'warning' },
  'android.permission.LAUNCH_CAPTURE_CONTENT_ACTIVITY_FOR_NOTE': { desc: '捕获内容活动', level: 'warning' },
  'android.permission.OBSERVE_SENSOR_PRIVACY': { desc: '观察传感器隐私', level: 'warning' },
  'android.permission.TOGGLE_SENSOR_PRIVACY': { desc: '切换传感器隐私', level: 'danger' },
  'android.permission.START_FOREGROUND_SERVICES_FROM_BACKGROUND': { desc: '后台启动前台服务', level: 'warning' },
  'android.permission.USE_FULL_SCREEN_INTENT': { desc: '全屏意图', level: 'warning' },
  'android.permission.REQUEST_COMPANION_RUN_IN_BACKGROUND': { desc: '伴侣后台运行', level: 'warning' },
  'android.permission.REQUEST_COMPANION_START_APP_SERVICES': { desc: '伴侣启动服务', level: 'warning' },
  'android.permission.REQUEST_COMPANION_PROFILE_WATCH': { desc: '伴侣手表配置', level: 'normal' },
  'android.permission.HIDE_OVERLAY_WINDOWS': { desc: '隐藏覆盖窗口', level: 'normal' },
  'android.permission.DELIVER_COMPANION_MESSAGES': { desc: '发送伴侣消息', level: 'warning' },
  'android.permission.ACCESS_ADSERVICES_ATTRIBUTION': { desc: '广告归因', level: 'warning' },
  'android.permission.ACCESS_ADSERVICES_AD_ID': { desc: '广告 ID', level: 'warning' },
  'android.permission.ACCESS_ADSERVICES_TOPICS': { desc: '广告主题', level: 'warning' },
  'android.permission.ACCESS_ADSERVICES_CUSTOM_AUDIENCE': { desc: '广告自定义受众', level: 'warning' },
  'android.permission.AD_ID': { desc: '广告标识符', level: 'warning' },
  'android.permission.READ_CLAMPG_SHELL': { desc: '读取 ClamPG Shell', level: 'warning' },
  'android.permission.USE_ICC_AUTH_WITH_CONTACTLESS_ACCESS': { desc: '非接触式 ICC 认证', level: 'warning' },
  'android.permission.READ_PRECISE_PHONE_STATE': { desc: '精确电话状态', level: 'danger' },
  'android.permission.START_ACTIVITIES_FROM_BACKGROUND': { desc: '后台启动活动', level: 'warning' },
  'android.permission.READ_PRIVILEGED_PHONE_STATE': { desc: '特权电话状态', level: 'danger' },
  'android.permission.MANAGE_OWN_CALLS': { desc: '管理自有通话', level: 'warning' },
  'android.permission.CAPTURE_AUDIO_OUTPUT': { desc: '捕获音频输出', level: 'danger' },
  'android.permission.CAPTURE_VIDEO_OUTPUT': { desc: '捕获视频输出', level: 'danger' },
  'android.permission.CAPTURE_SECURE_VIDEO_OUTPUT': { desc: '捕获安全视频', level: 'danger' },
  'android.permission.MEDIA_CONTENT_CONTROL': { desc: '媒体内容控制', level: 'danger' },
  'android.permission.ACCESS_NOTIFICATIONS': { desc: '访问通知', level: 'danger' },
  'android.permission.BIND_REMOTEVIEWS': { desc: '绑定远程视图', level: 'warning' },
  'android.permission.BIND_MIDI_DEVICE_SERVICE': { desc: '绑定 MIDI 服务', level: 'normal' },
  'android.permission.BIND_PRINT_SERVICE': { desc: '绑定打印服务', level: 'normal' },
  'android.permission.BIND_TV_INPUT': { desc: '绑定电视输入', level: 'warning' },
  'android.permission.BIND_VOICE_INTERACTION': { desc: '绑定语音交互', level: 'warning' },
  'android.permission.BIND_VPN_SERVICE': { desc: '绑定 VPN 服务', level: 'warning' },
  'android.permission.BIND_NFC_SERVICE': { desc: '绑定 NFC 服务', level: 'warning' },
  'android.permission.READ_DREAM_STATE': { desc: '读取屏保状态', level: 'normal' },
  'android.permission.WRITE_DREAM_STATE': { desc: '修改屏保状态', level: 'warning' },
  'android.permission.ALLOCATE_AGGRESSIVE': { desc: '分配激进资源', level: 'warning' },
  'android.permission.BACKUP': { desc: '备份', level: 'warning' },
  'android.permission.CONFIRM_FULL_BACKUP': { desc: '确认完整备份', level: 'warning' },
  'android.permission.READ_AUTO_FILL_DATA': { desc: '读取自动填充数据', level: 'danger' },
  'android.permission.WRITE_AUTO_FILL_DATA': { desc: '修改自动填充数据', level: 'danger' },
  'android.permission.REQUEST_OBSERVE_COMPANION_DEVICE_PRESENCE': { desc: '观察伴侣设备', level: 'warning' },
  'android.permission.BLUETOOTH_PRIVILEGED': { desc: '蓝牙特权', level: 'danger' },
  'android.permission.LOCATION_HARDWARE': { desc: '硬件定位', level: 'danger' },
  'android.permission.ACCESS_BLOBS_ACROSS_USERS': { desc: '跨用户数据块', level: 'danger' },
  'android.permission.MANAGE_MEDIA': { desc: '管理媒体', level: 'danger' },
  'android.permission.CALL_COMPANION_APP': { desc: '通话伴侣应用', level: 'warning' },
  'android.permission.START_VIEW_PERMISSION_USAGE': { desc: '查看权限使用', level: 'warning' },
  'android.permission.PROVIDE_RESOLVER_RANKER_SERVICE': { desc: '解析排序服务', level: 'warning' },
  'android.permission.MANAGE_APP_OPS_MODES': { desc: '管理应用操作模式', level: 'danger' },
  'android.permission.GRANT_RUNTIME_PERMISSIONS': { desc: '授予运行时权限', level: 'danger' },
  'android.permission.UPDATE_DEVICE_STATS': { desc: '更新设备统计', level: 'danger' },
  'android.permission.NETWORK_SETTINGS': { desc: '网络设置', level: 'danger' },
  'android.permission.ACCESS_INPUT_FLINGER': { desc: '访问 InputFlinger', level: 'danger' },
  'android.permission.REBOOT': { desc: '重启设备', level: 'danger' },
  'android.permission.HARDWARE_TEST': { desc: '硬件测试', level: 'danger' }
}

const LEVEL_LABELS = {
  danger: '敏感',
  warning: '中等',
  normal: '常规'
}

const LEVEL_COLORS = {
  danger: '#ff4d4f',
  warning: '#faad14',
  normal: '#52c41a'
}

export function getPermissionInfo (permName) {
  const entry = PERMISSIONS_MAP[permName]
  if (entry) {
    return { desc: entry.desc, level: entry.level, levelLabel: LEVEL_LABELS[entry.level], levelColor: LEVEL_COLORS[entry.level] }
  }
  return { desc: '未知权限', level: 'normal', levelLabel: '未知', levelColor: '#999' }
}
